apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
spec:
  containers:
  - name: inspector
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /data
      name: my-pvc
  volumes:
  - name: my-pvc
    persistentVolumeClaim:
      claimName: forgejo-runner-docker-storage