apiVersion: v1
kind: Service
metadata:
  name: tansu
  labels:
    app: tansu
spec:
  ports:
  - port: 9092
    name: kafka
    targetPort: 9092
  - port: 9100
    name: metrics
    targetPort: 9100
  selector:
    app: tansu
